spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

